# generate-report.ps1

$date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# محتوى التقرير بصيغة HTML
$html = @"
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Daily Report</title>
  <style>
    body { font-family: Arial; }
    h1 { color: #4CAF50; }
    .status { color: green; font-weight: bold; }
  </style>
</head>
<body>
  <h1>Daily Report</h1>
  <p>✅ Script ran successfully on: <strong>$date</strong></p>
  <ul>
    <li>Logs processed: 10</li>
    <li>Status: <span class="status">OK</span></li>
  </ul>
  <hr>
  <p>Generated by GitHub Actions 🚀</p>
</body>
</html>
"@

# يحفظ الملف باسم report.html
$html | Set-Content -Path report.html
