name: Deploy Website to IIS

on:
  push:
    branches:
      - main   # كل تحديث على main يعمل ديبلويمنت
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted   # السيرفر اللي عليه IIS والـ runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run deployment script
        run: pwsh ./deploy/run.ps1
