name: Simple IIS Deployment

on:
  push:
    branches: [main, site]
  workflow_dispatch: {}   # للتشغيل اليدوي من GitHub

jobs:
  deploy:
    runs-on: self-hosted   # يشغل على الـ runner في جهازك

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set PowerShell policy (temporary for this job)
        shell: pwsh
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

      - name: Run deployment script
        shell: pwsh
        run: ./deploy/run.ps1
