name: Deploy to IIS with Rollback

on:
  workflow_dispatch:  # يمكنك تشغيله يدويًا من GitHub

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files (Debug)
        run: dir

      - name: Run deployment script
        run: powershell -File ./deploy/run.ps1

      - name: Upload latest backup (optional)
        uses: actions/upload-artifact@v4
        with:
          name: iis-backup
          path: C:\backup
