name: Test CSV Read

on:
  workflow_dispatch:

jobs:
  test_read_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files to debug
        run: ls -la

      - name: Generate HTML report
        run: pwsh ./debug-csv.ps1

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: report.html
